### ISSUE TITLE
set data-url

### ISSUE THREAD

**Issue by comtronix** [kyco/jquery.kyco.easyshare#2]
is it posible to set the data url dynamicly?
i have content in a div loaded by button. i want to share the content on social with your share buttons.

i tried, but the -share- points to the first page and not to the content.
I use window.history.pushState to change the adres in the browser bar.
$("#easyshare").attr("data-easyshare-url","link to page");

cant figger out what i am doing wrong.

**Comment by Corhero** [comment]
Hi

Sorry for only replying so late. I will take a look at this as soon as I can.

**Comment by Corhero** [comment]
Hey. Are you still struggling? The plugin triggers on pageload. You can manually change that, i.e. remove the `$(document).ready(function() {})` at the bottom of the script. You can then simply call `kyco.easyShare()` after you have changed the `data-easyshare-url`. Hope that helps.
