### ISSUE TITLE
twitter count not display

### ISSUE THREAD

**Issue by Neerajt43** [kyco/jquery.kyco.easyshare#4]
Twitter share count not display and share image not display

**Comment by Corhero** [comment]
Hi, thanks. Will look into this.

**Comment by Corhero** [comment]
Twitter has officially discontinued their "share" count URL. I will most probably remove the count from this plugin. The only way to get the count now is through unofficial means which I don't think I will implement.

**Comment by DistinctiveThemes** [comment]
@Neerajt43 having the same trouble - it seems http://opensharecount.com/ can help. Im working on a fix now so will let you know if I get any luck with it

**Comment by Neerajt43** [comment]
I want display total count seprate
