### ISSUE TITLE
facebook count does not display

### ISSUE THREAD

**Issue by Neerajt43** [kyco/jquery.kyco.easyshare#5]
i have install your plugin but facebook count is not display in your plugin please help me...

**Comment by Corhero** [comment]
Hi, will check it out as soon as I have time.

**Comment by sanixo** [comment]
to solve facebook share count update get_fb_shares_count function on api/easyshare.php

  function get_fb_shares_count($url) {
    $file_contents = @file_get_contents(FACEBOOK_API_URL . $url);
    $response      = json_decode($file_contents, true);

    if (isset($response[$url]['share'])) {
      return intval($response[$url]['share']['share_count']);
    }

    return 0;
  }

**Comment by caweidmann** [comment]
Hi, thank you for the fix and sorry for the long delay! The fix is in the latest version 1.3.2.
